image: node:22

stages:
  - test
  - build

before_script:
  - apt-get update
  - apt-get install -y python3 make g++ openjdk-17-jdk

test_job:
  stage: test
  script:
    - echo "Skipping tests"

build_android:
  stage: build
  script:
    - npm ci
    - npm run build
    - npx cap sync android
    - cd android
    - chmod +x gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk
